[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "explore-this"
version = "0.1"
description = "Explore This! beat tracker"
readme = "README.md"
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
]
authors = [
    {name = "Robert Kihlborg", email = "robert.olsson.kihlborg@gmail.com"},
    {name = "Francesco Foscarin", email = "francesco.foscarin@jku.at"},
    {name = "Jan Schlüter", email = "jan.schlueter@jku.at"},
]
requires-python = ">=3"
dependencies = [
    "numpy>=1.20",
    "torch>=2",
    "torchaudio",
    "einops",
    "rotary-embedding-torch",
    "soxr",
]
license = "MIT"
license-files = ["LICENSE"]

[tool.setuptools.package-dir]
explore_this = "explore_this"

[project.urls]
Repository = "https://github.com/CPJKU/explore_this"
Issues = "https://github.com/CPJKU/explore_this/issues"

